config/routes.rb
Scaintera::Application.routes.draw do
  resource :user_sessions, :calculator
  resources :policy_holders, :users, :beneficiaries
  resources :settings do
    collection do
      post "prices"
      post "reset"
    end
  end
  match '/' => 'policy_holders#index'
end

app/models/beneficiary.rb
require 'enumerated_attribute'

class Beneficiary < ActiveRecord::Base
  belongs_to :policy_holder
  validates_presence_of :surname, :names, :dob, :plan

  enum_attr :plan, %w(young_active young_semi_active senior_active senior_semi_active),
            :init => :young_active, :nil => false do
              label young_active: "Personne de 0 a 55, active"
              label young_semi_active: "Personne de 0 a 55, mi-active"
              label senior_active: "Personne de 56 a 70, active"
              label senior_semi_active: "Personne de 56 a 70, mi-active"
  end

  def full_name
    names + " " + surname
  end

end

app/controllers/beneficiaries_controller.rb
class BeneficiariesController < ApplicationController

  def per_page
    @per_page = params[:per_page] || 15
  end

  def page
    params[:page] || 1
  end

  def index
    search = BeneficiarySearch.new(params[:s])
    @beneficiaries = search.execute(page, per_page, current_user)
  end

end

app/views/beneficiaries/_search.html.haml
#search-bar{style: "padding-top: 10px"}
  %form.search{:method=>"get", style: "margin-left: 10px"}
    %input{:type=>"text", :id=>"query", :name=>"s[name]"}
    .aoq-wrapper
      .aoq
    %button.search-button
      %div
        = image_tag "search_white.png"
  #advanced
    %a.close-button
    = form_for :s, :method => "get" do |f|
      .simple-search
        %label
          Prénoms
        = f.text_field :names
        %label
          Nom
        = f.text_field :surname
        %label
          Contact
        = f.text_field :telephone
        %label
          Date de Naissance
        = f.text_field :dob
      %button.search-button{:style=>"margin-top: 15px; margin-left: -3px"}
        %div
          = image_tag "search_white.png"
    .clear

app/views/beneficiaries/index.html.haml
= content_for :title, "Beneficiary Search"

.block
  .block_content
    #portlets
      %span.logo
        = image_tag "logo.png", style: "width: 50px"
      .clear
      .portlet
        .portlet-content.nopadding
          %div
            = render :partial => "search"
          %table
            %thead
              %tr
                %th Assuré
                %th Noms et Prénoms
                %th Date de Naissance
                %th Contact
                %th Plan
            %tbody
              - for beneficiary in @beneficiaries
                %tr
                  %td
                    = link_to beneficiary.policy_holder.names + " " + beneficiary.policy_holder.surname, edit_policy_holder_path(beneficiary.policy_holder)
                  %td
                    = beneficiary.names + " " + beneficiary.surname
                  %td= beneficiary.dob.strftime("%Y-%m-%d")
                  %td= beneficiary.telephone
                  %td
          .clear
          #pagination-wrapper
            = will_paginate @policies, :params => @params, :outer_window => 1, :inner_window => 1, :class => "paggination"
            %span#pagination-counter
              = page_entries_info(@policies)
            .clear
:javascript
  $(function() {
    new App.Views.Search({el: "#search-bar"});
  })