config/routes.rb
Scaintera::Application.routes.draw do
  resource :user_sessions, :calculator
  resources :policy_holders, :users, :beneficiaries
  resources :settings do
    collection do
      post "prices"
      post "reset"
    end
  end
  match '/' => 'policy_holders#index'
end

app/views/policies/beneficiaries.html.haml
= content_for :title, "Policy Beneficiaries"

= content_for :search do
  =render :partial => "search"

.block
  .block_content
    #portlets
      .portlet{style: "border-top: 0; border-left: 0; border-right: 0"}
        .portlet-content.nopadding
          %h2
            = "Policy ##{@policy.id}"
          %br
          %ul#tabs.tabs
            %li.available= link_to "Policy", policy_path(@policy)
            %li.available= link_to "Policy Holder", policy_holder_path(@policy)
            %li.active= link_to "Beneficiaries", "#"
            %li= link_to "Comments", policy_comments_path(@policy)
          #beneficiaries.tab
            %table{style: "border: 1px solid #ccc"}
              %thead
                %th
                %th Names
                %th Surname
                %th Relationship
                %th Telephone
                %th Date of Birth
                %th
              %tbody
                - for beneficiary in @policy.beneficiaries
                  %tr{:"data-id" => beneficiary.id}
                    %td{style: "padding: 2px"}
                      %a{class: 'remove', title: "Remove beneficiary", style: 'display: block; height: 25px; width: 24px; background: url(https://ssl.gstatic.com/ui/v1/icons/mail/sprite_black2.png) no-repeat -61px -41px transparent', href: '#'}
                    %td
                      %input{type: "text", name: "names", style: "border: 1px solid #efefef", value: beneficiary.names}
                    %td
                      %input{type: "text", name: "surname", style: "border: 1px solid #efefef; width: 100px", value: beneficiary.surname}
                    %td
                      %input{type: "text", name: "relationship", style: "border: 1px solid #efefef; width: 100px", value: beneficiary.relationship}
                    %td
                      %input{type: "text", name: "telephone", style: "border: 1px solid #efefef", value: beneficiary.telephone}
                    %td
                      %input.date_picker{type: "text", name: "dob", style: "border: 1px solid #efefef; width: 100px", value: beneficiary.dob.strftime("%Y-%m-%d")  }
                    %td{style: "padding: 2px"}
                      %a{class: 'save', title: "Save your changes", style: 'display: block; height: 25px; width: 24px; background: url(https://ssl.gstatic.com/ui/v1/icons/mail/sprite_black2.png) no-repeat -2px -19px transparent', href: '#'}
            .errors{style: "margin-bottom: 12px; display: none"}
            .toolbar{:style=>"margin-bottom: 10px"}
              %button.gray-button.add
                %div{style: "width: 130px"} Add Beneficiary
:javascript
  $(function() {
    $(".date_picker").datepicker({dateFormat: 'yy-mm-dd'});
    $('#beneficiaries .save').tipsy({gravity: 'w'});
    $('#beneficiaries .remove').tipsy({gravity: 'e'});
    new App.Views.BeneficiaryEditor({el: "#beneficiaries", policy_id: #{@policy.id}});
  });